language: go
go:
- 1.11.x
env:
- GO111MODULE=on
before_script:
- bash ./x/lint.sh
notifications:
  email: false
script: bash ./x/coverage.sh
after_success: bash ./x/upload_coverage.sh bash <(curl -s https://codecov.io/bash)
