// Code generated by github.com/tvastar/test/cmd/testmd/testmd.go. DO NOT EDIT.

package main_test

import (
	"fmt"
	"runtime"
	"testing"
)

func Example_1() {

	if len("hello") != 5 {
		fmt.Println("This should not happen")
	}

	// Output:

}

func TestBoo(t *testing.T) {

	// import runtime
	_, fname, _, _ := runtime.Caller(1)
	if fname == "" {
		t.Error("Could not find caller info")
	}

}

func stranger() string {
	return "stranger"
}
func Example_UsingSomethingDefinedInGlobal() {

	fmt.Println("ok", stranger())

	// Output: ok stranger

}
